### ISSUE TITLE
Feature request: add Makefile

### ISSUE THREAD

**Issue by lifepillar** [cmosher01/DskToWoz2#1]
Planning to add a Makefile to this project? Or at least some build instructions in the Readme…

**Comment by cmosher01** [comment]
The Makefile is generated by qmake (from Qt), based on the .pro file. Also, I've created a Travis build that generates binaries and creates releases. And I added a link for Qt Getting Started, to the Readme.

**Comment by lifepillar** [comment]
Thanks, that works. I have added dsktowoz2 to https://github.com/lifepillar/homebrew-appleii.

**Comment by cmosher01** [comment]
@lifepillar, thanks. That's great.
