### ISSUE TITLE
DLL dependencies for windows build

### ISSUE THREAD

**Issue by bbbradsmith** [cmosher01/DskToWoz2#2]
The latest release is just an EXE, and it has many dependent DLLs needed to run. Could you provide information on where to find the correct versions of the the required DLLs? I know it needs at least the following:

* libgcc_s_seh-1.dll
* libGLESv2.dll
* libstdc++-6.dll
* libwinpthread-1.dll
* Qt5Core.dll
* Qt5Gui.dll
* Qt5Widgest.dll

Not sure if there are more, but this is all that the program has asked for while trying to start it. I could find some version of each of these included with other applications I have installed (e.g. RetroArch, OBS) but apparently one or more of them does not match your expected version, I get:

"The procedure entry point _ZN10OArrayData10deallocateEPS_yy could not be located in the dynamic link library ...\dsktowoz2.exe"

**Comment by ebadger** [comment]
super tempted to fork this project and add a command line interface - looking at the GUI code, it looks pretty simple.

**Comment by cmosher01** [comment]
Depends on QT 5, as stated in README. https://doc.qt.io/qt-5/gettingstarted.html
